name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x # Change to the desired Flutter version

      - name: Update Dart SDK Constraint
        run: |
          echo "environment:" >> pubspec.yaml
          echo "  sdk: \">=2.16.2 <3.0.0\"" >> pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
